Use `refines_constraint_value` if available (#10)
* Let `compat_constraint_setting` use `refines_constraint_value` if
Bazel supports it. This required fixes to the value and bazel_deps.
* Drop `*_not_available` defaults to improve the error message in case
of a missing refined value:
```
ERROR: /Users/fmeum/git/platforms_contrib/examples/libc/BUILD.bazel:14:9: in constraint_values attribute of platform rule //libc:legacy_linux: constraint_value @platforms_contrib//os/linux/libc/glibc:at_least_2.16_available refines @platforms_contrib//os/linux/libc/glibc:at_least_2.15_available, but platform //libc:legacy_linux sets the conflicting constraint_value @platforms_contrib//os/linux/libc/glibc:at_least_2.15_not_available for @platforms_contrib//os/linux/libc/glibc:at_least_2.15
```
becomes
```
ERROR: /Users/fmeum/git/platforms_contrib/examples/libc/BUILD.bazel:14:9: in constraint_values attribute of platform rule //libc:legacy_linux: constraint_value @platforms_contrib//os/linux/libc/glibc:at_least_2.16_available refines @platforms_contrib//os/linux/libc/glibc:at_least_2.15_available, but platform //libc:legacy_linux does not set the latter. Fix with:
  buildozer 'add constraint_values @platforms_contrib//os/linux/libc/glibc:at_least_2.15_available' //libc:legacy_linux
```